[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "t4n-manpy"
version = "1.0.0"
description = "T4n-Manpy: Python-based package manager for Void Linux"
requires-python = ">=3.8"
dependencies = [
    "rich",
    "argparse"
]
